// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package kubectl

import (
	"github.com/angelokurtis/kts-cli/internal/kube"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/kubernetes/typed/extensions/v1beta1"
)

// Injectors from wire_inj.go:

func newDiscovery() (discovery.DiscoveryInterface, error) {
	config, err := kube.NewRestConfig()
	if err != nil {
		return nil, err
	}
	discoveryClient, err := kube.NewDiscoveryClient(config)
	if err != nil {
		return nil, err
	}
	return discoveryClient, nil
}

func newExtensions() (v1beta1.ExtensionsV1beta1Interface, error) {
	config, err := kube.NewRestConfig()
	if err != nil {
		return nil, err
	}
	clientset, err := kube.NewClientset(config)
	if err != nil {
		return nil, err
	}
	extensionsV1beta1Interface := kube.NewExtensions(clientset)
	return extensionsV1beta1Interface, nil
}
